app/models.py
from app.plugins import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.Binary)

app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.html5 import EmailField
from wtforms.fields import PasswordField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    email = EmailField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])


class RegisterUserForm(FlaskForm):
    email = EmailField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])
    confirm_password = PasswordField(validators=[DataRequired()])

app/__init__.py
from app.instance import create_app
from app.config import app_config
import os

application = create_app(app_config[os.getenv('APP_CONFIG')])
application.app_context().push()

if __name__ == '__main__':
    application.run()

app/views.py
from flask import Blueprint
from flask import request
from flask import render_template
from flask import flash
from flask import redirect
from flask import url_for
from flask import jsonify
from flask import abort
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user

from app.plugins import login_manager

from app.models import User
from app.forms import LoginForm, RegisterUserForm
from app.plugins import db

app_views = Blueprint('views', __name__, url_prefix='/')


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@app_views.route("login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        user = User.query.filter(User.email == form.email.data,
                                 User.password == bytes(form.password.data, encoding='utf-8'))\
            .first()
        if form.validate_on_submit() and user.is_active:
            login_user(user)
            return redirect(url_for("views.dashboard"))
        flash(form.errors, 'error')
        return redirect(url_for('views.login'))
    context = {
        'form': form
    }
    return render_template("views/login.html", **context)


@app_views.route("logout")
def logout():
    logout_user()
    return redirect(url_for("views.index"))


@app_views.route("forgot_password")
def forgot_password():
    return


@app_views.route("register", methods=['GET', 'POST'])
def register():
    form = RegisterUserForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.password.data != form.confirm_password.data:
                flash("Password does not match.", "error")
                return redirect(url_for("views.register"))
            user = User.query.filter(User.email == form.email.data).first()
            if user:
                flash("Email already taken.", "error")
                return redirect(url_for("views.register"))
            new_user = User(email=form.email.data, password=bytes(form.password.data, encoding='utf-8'))
            db.session.add(new_user)
            db.session.commit()
            flash("Registration successful.", "success")
            return redirect(url_for("views.register"))

        flash(form.errors, "error")
        return redirect(url_for("views.register"))
    context = {
        'form': form
    }
    return render_template("views/register.html", **context)


@app_views.route('')
def index():
    context = {}
    return render_template("views/index.html", **context)


@app_views.route("dashboard")
@login_required
def dashboard():
    context = {}
    return render_template("views/dashboard.html", **context)

app/templates/views/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} FB Proxy {% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block extra_css %} {% endblock %}
</head>
<body>
{% block content %} {% endblock %}
</body>
</html>

app/templates/views/dashboard.html
{% extends "views/base.html" %}
{% block title %} {{super()}} | Dashboard {% endblock %}

{% block content %}
{% endblock %}

app/templates/views/index.html
{% extends "views/base.html" %}

app/templates/views/login.html
{% extends "views/base.html" %}
{% block title %} {{super()}} - Login {% endblock %}
{% block extra_css %}
    <style>
        body{
            background: #f8f9fa;
        }
        .row > div{
            background: #FFF;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 border m-5 p-3 mx-auto box-shadow rounded">
                <h2 class="border-bottom p-2 mb-4 text">Login <small class="text" style="font-size:14px;">into your account.</small></h2>
            {% with errors = get_flashed_messages(category_filter=["error"]) %}
            {% if errors %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <ul class="list-unstyled">
                    {%- for msg in errors %}
                    <li>{{ msg }}</li>
                    {% endfor -%}
                </ul>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endwith %}
                <form method="post" class="m-4">
                    <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                    <div class="form-row">
                        <div class="form-group col-md-12 p-2">
                            <label><span class="fa fa-envelope"></span>&nbsp;&nbsp;Email</label>
                            {{form.email(class="form-control")}}
                        </div>
                    </div>
                     <div class="form-row">
                        <div class="form-group col-md-12 p-2">
                            <label><span class="fa fa-lock"></span>&nbsp;&nbsp;Password</label>
                            {{form.password(class="form-control")}}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary"><span class="fa fa-sign-in"></span> Login</button>
                     &nbsp;&nbsp;&nbsp;<a href="{{url_for('views.forgot_password')}}">Forgot Password?</a>
                </form>
                <p class="text text-center m-3 border-top p-3">Don't have an account? <a href="{{url_for('views.register')}}">Sign up.</a></p>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/views/register.html
{% extends "views/base.html" %}
{% block title %} {{super()}} - Register {% endblock %}
{% block extra_css %}
<style>
        body{
            background: #f8f9fa;
        }
        .row > div{
            background: #FFF;
        }


</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 border m-5 p-3 mx-auto box-shadow rounded">
            <h2 class="border-bottom p-2 mb-4 text">Sign up</h2>
            {% with errors = get_flashed_messages(category_filter=["error"]) %}
            {% if errors %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <ul class="list-unstyled">
                    {%- for msg in errors %}
                    <li>{{ msg }}</li>
                    {% endfor -%}
                </ul>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endwith %}
            <form method="post" class="m-4">
                <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                <div class="form-row">
                    <div class="form-group col-md-12 p-2">
                        <label><span class="fa fa-envelope"></span>&nbsp;&nbsp;Email</label>
                        {{form.email(class="form-control")}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 p-2">
                        <label><span class="fa fa-lock"></span>&nbsp;&nbsp;Password</label>
                        {{form.password(class="form-control")}}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 p-2">
                        <label><span class="fa fa-lock"></span>&nbsp;&nbsp;Confirm Password</label>
                        {{form.confirm_password(class="form-control")}}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary"><span class="fa fa-sign-in"></span> Sign up</button>
            </form>
            <p class="text text-center m-3 border-top p-3">Already have an account? <a
                    href="{{url_for('views.login')}}">Login.</a></p>
        </div>
    </div>
</div>
{% endblock %}